In [2]:
import torch
x = torch.tensor([[[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]],
                  [[13., 14., 15.], [16., 17., 18.], [19., 20., 21.], [22., 23., 24.]]])

mean = x.mean(dim=-1, keepdim=True)
std = x.std(dim=-1, keepdim=True)


c:\Projects\transformer\myenv\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
print(mean)
print(std)

tensor([[[ 2.],
         [ 5.],
         [ 8.],
         [11.]],

        [[14.],
         [17.],
         [20.],
         [23.]]])
tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])


In [10]:
st = "aababsdfg"

left =0 
maxlength =0
seen = set()

for right in range(len(st)):
    while st[right] in seen:
        seen.remove(st[left])
        left+=1

    seen.add(st[right])

    maxlength = max(maxlength,right-left+1)
print(maxlength)

6


In [13]:
inp=[1,2,4,5]
target = 9
dic = {}
for i,num in enumerate(inp):
    if (target - num) not in dic:
        dic[num] = i
    else:
        print(dic[target - num],i)


2 3


In [20]:
import numpy as np
s=np.array([[1,2,3,4,1],[1,2,6,4,3],[5,5,6,8,7],[5,5,6,8,7]])
s[:,::2]

array([[1, 3, 1],
       [1, 6, 3],
       [5, 6, 7],
       [5, 6, 7]])

In [21]:
s[::2,:]

array([[1, 2, 3, 4, 1],
       [5, 5, 6, 8, 7]])

In [32]:
s= 'cbabcdf'
ML = 0
for center in range(1,len(s)):
    i =1
    while s[center-i:center+i+1] == s[center-i:center+i+1][::-1] and (center-i)>=0 and (center+i)<len(s):
        ML=max(ML,len(s[center-i:center+i+1]))
        i+=1
        
print(ML)

5


In [36]:
s = np.array([1,'sdf'])

AttributeError: 'numpy.ndarray' object has no attribute 'type'